domain: KyusonLim/design_ksl
url: https://kyusonlim.github.io/design_ksl/gallery.html

title: Misong
email: goldmuto@gmail.com
author: Kyuson

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9" 

# disqus:
#   shortname: example-com
#
# rrss:
  # discord: hoola
  # facebook: hola
  # twitter: Hola
  # instagram: Hola
  # linkedin: Hola
  # pinterest: hola
  # whatsapp: 123
  # telegram: 123
  # email: email
